global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'servidor'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'aplicacion_nodejs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']