sonar.projectKey=pugaoficial22-crypto_example-node
sonar.projectName=Fast API Dev
sonar.projectVersion=1.0

# 1. Asegúrate de que estas carpetas existan en la raíz
sonar.sources=src,routes,app.js,lib
sonar.tests=tests

# 2. Forzamos la exclusión de TODO lo que no sea código fuente real
sonar.exclusions=**/node_modules/**,**/coverage/**,**/public/**,**/bin/**,**/*.html

# 3. Ruta del reporte de cobertura
# Verifica si la carpeta es 'fast-api-dev/coverage' o solo 'coverage'
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8