sonar.projectKey=pugaoficial22-crypto_example-node
sonar.projectName=Fast API Dev
sonar.projectVersion=1.0

# Esto le dice a Sonar que busque el código DENTRO de la carpeta
sonar.sources=fast-api-dev
sonar.tests=fast-api-dev/tests

# EXCLUSIONES: Esto es lo que borrará los 233 errores de golpe
sonar.exclusions=fast-api-dev/node_modules/**, fast-api-dev/coverage/**, **/load_test.js, **/*.html

# Ruta al reporte de cobertura (ajustada a tu carpeta)
sonar.javascript.lcov.reportPaths=fast-api-dev/coverage/lcov.info

sonar.sourceEncoding=UTF-8