sonar.projectKey=pugaoficial22-crypto_example-node
sonar.projectName=Fast API Dev
sonar.projectVersion=1.0

# Solo analizamos la carpeta del proyecto
sonar.sources=fast-api-dev
sonar.tests=fast-api-dev/tests

# Exclusiones para limpiar los 223 errores
sonar.exclusions=**/node_modules/**, **/coverage/**, **/public/**, **/bin/**, **/*.html, load_test.js

# Ruta de cobertura que ya vimos que funciona
sonar.javascript.lcov.reportPaths=fast-api-dev/coverage/lcov.info

sonar.sourceEncoding=UTF-8